/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppsCompanyIdRouteRouteImport } from './routes/apps/$companyId/route'
import { Route as AppsCompanyIdIndexRouteImport } from './routes/apps/$companyId/index'
import { Route as AuthSignUpSplatRouteImport } from './routes/auth/sign-up.$'
import { Route as AppsCompanyIdTrackingIndexRouteImport } from './routes/apps/$companyId/tracking/index'
import { Route as AppsCompanyIdOrdersIndexRouteImport } from './routes/apps/$companyId/orders/index'
import { Route as AppsCompanyIdMembersIndexRouteImport } from './routes/apps/$companyId/members/index'
import { Route as AppsCompanyIdFleetsIndexRouteImport } from './routes/apps/$companyId/fleets/index'
import { Route as AppsCompanyIdDriversIndexRouteImport } from './routes/apps/$companyId/drivers/index'
import { Route as AppsCompanyIdDispatchIndexRouteImport } from './routes/apps/$companyId/dispatch/index'
import { Route as AppsCompanyIdDashboardIndexRouteImport } from './routes/apps/$companyId/dashboard/index'
import { Route as AppsCompanyIdBillingIndexRouteImport } from './routes/apps/$companyId/billing/index'
import { Route as AppsCompanyIdOrdersCreateRouteImport } from './routes/apps/$companyId/orders/create'
import { Route as AppsCompanyIdOrdersOrderRefIndexRouteImport } from './routes/apps/$companyId/orders/$orderRef/index'
import { Route as AppsCompanyIdFleetsVehicleIdIndexRouteImport } from './routes/apps/$companyId/fleets/$vehicleId/index'
import { Route as AppsCompanyIdDriversDriverIdIndexRouteImport } from './routes/apps/$companyId/drivers/$driverId/index'
import { Route as AppsCompanyIdBillingHistoryIndexRouteImport } from './routes/apps/$companyId/billing/history/index'
import { Route as AppsCompanyIdOrdersOrderRefEditRouteImport } from './routes/apps/$companyId/orders/$orderRef/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsCompanyIdRouteRoute = AppsCompanyIdRouteRouteImport.update({
  id: '/apps/$companyId',
  path: '/apps/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsCompanyIdIndexRoute = AppsCompanyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsCompanyIdRouteRoute,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/auth/sign-up/$',
  path: '/auth/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsCompanyIdTrackingIndexRoute =
  AppsCompanyIdTrackingIndexRouteImport.update({
    id: '/tracking/',
    path: '/tracking/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdOrdersIndexRoute =
  AppsCompanyIdOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdMembersIndexRoute =
  AppsCompanyIdMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdFleetsIndexRoute =
  AppsCompanyIdFleetsIndexRouteImport.update({
    id: '/fleets/',
    path: '/fleets/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdDriversIndexRoute =
  AppsCompanyIdDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdDispatchIndexRoute =
  AppsCompanyIdDispatchIndexRouteImport.update({
    id: '/dispatch/',
    path: '/dispatch/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdDashboardIndexRoute =
  AppsCompanyIdDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdBillingIndexRoute =
  AppsCompanyIdBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdOrdersCreateRoute =
  AppsCompanyIdOrdersCreateRouteImport.update({
    id: '/orders/create',
    path: '/orders/create',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdOrdersOrderRefIndexRoute =
  AppsCompanyIdOrdersOrderRefIndexRouteImport.update({
    id: '/orders/$orderRef/',
    path: '/orders/$orderRef/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdFleetsVehicleIdIndexRoute =
  AppsCompanyIdFleetsVehicleIdIndexRouteImport.update({
    id: '/fleets/$vehicleId/',
    path: '/fleets/$vehicleId/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdDriversDriverIdIndexRoute =
  AppsCompanyIdDriversDriverIdIndexRouteImport.update({
    id: '/drivers/$driverId/',
    path: '/drivers/$driverId/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdBillingHistoryIndexRoute =
  AppsCompanyIdBillingHistoryIndexRouteImport.update({
    id: '/billing/history/',
    path: '/billing/history/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdOrdersOrderRefEditRoute =
  AppsCompanyIdOrdersOrderRefEditRouteImport.update({
    id: '/orders/$orderRef/edit',
    path: '/orders/$orderRef/edit',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/$companyId': typeof AppsCompanyIdRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/register/': typeof RegisterIndexRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/apps/$companyId/': typeof AppsCompanyIdIndexRoute
  '/apps/$companyId/orders/create': typeof AppsCompanyIdOrdersCreateRoute
  '/apps/$companyId/billing/': typeof AppsCompanyIdBillingIndexRoute
  '/apps/$companyId/dashboard/': typeof AppsCompanyIdDashboardIndexRoute
  '/apps/$companyId/dispatch/': typeof AppsCompanyIdDispatchIndexRoute
  '/apps/$companyId/drivers/': typeof AppsCompanyIdDriversIndexRoute
  '/apps/$companyId/fleets/': typeof AppsCompanyIdFleetsIndexRoute
  '/apps/$companyId/members/': typeof AppsCompanyIdMembersIndexRoute
  '/apps/$companyId/orders/': typeof AppsCompanyIdOrdersIndexRoute
  '/apps/$companyId/tracking/': typeof AppsCompanyIdTrackingIndexRoute
  '/apps/$companyId/orders/$orderRef/edit': typeof AppsCompanyIdOrdersOrderRefEditRoute
  '/apps/$companyId/billing/history/': typeof AppsCompanyIdBillingHistoryIndexRoute
  '/apps/$companyId/drivers/$driverId/': typeof AppsCompanyIdDriversDriverIdIndexRoute
  '/apps/$companyId/fleets/$vehicleId/': typeof AppsCompanyIdFleetsVehicleIdIndexRoute
  '/apps/$companyId/orders/$orderRef/': typeof AppsCompanyIdOrdersOrderRefIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/register': typeof RegisterIndexRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/apps/$companyId': typeof AppsCompanyIdIndexRoute
  '/apps/$companyId/orders/create': typeof AppsCompanyIdOrdersCreateRoute
  '/apps/$companyId/billing': typeof AppsCompanyIdBillingIndexRoute
  '/apps/$companyId/dashboard': typeof AppsCompanyIdDashboardIndexRoute
  '/apps/$companyId/dispatch': typeof AppsCompanyIdDispatchIndexRoute
  '/apps/$companyId/drivers': typeof AppsCompanyIdDriversIndexRoute
  '/apps/$companyId/fleets': typeof AppsCompanyIdFleetsIndexRoute
  '/apps/$companyId/members': typeof AppsCompanyIdMembersIndexRoute
  '/apps/$companyId/orders': typeof AppsCompanyIdOrdersIndexRoute
  '/apps/$companyId/tracking': typeof AppsCompanyIdTrackingIndexRoute
  '/apps/$companyId/orders/$orderRef/edit': typeof AppsCompanyIdOrdersOrderRefEditRoute
  '/apps/$companyId/billing/history': typeof AppsCompanyIdBillingHistoryIndexRoute
  '/apps/$companyId/drivers/$driverId': typeof AppsCompanyIdDriversDriverIdIndexRoute
  '/apps/$companyId/fleets/$vehicleId': typeof AppsCompanyIdFleetsVehicleIdIndexRoute
  '/apps/$companyId/orders/$orderRef': typeof AppsCompanyIdOrdersOrderRefIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/$companyId': typeof AppsCompanyIdRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/register/': typeof RegisterIndexRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/apps/$companyId/': typeof AppsCompanyIdIndexRoute
  '/apps/$companyId/orders/create': typeof AppsCompanyIdOrdersCreateRoute
  '/apps/$companyId/billing/': typeof AppsCompanyIdBillingIndexRoute
  '/apps/$companyId/dashboard/': typeof AppsCompanyIdDashboardIndexRoute
  '/apps/$companyId/dispatch/': typeof AppsCompanyIdDispatchIndexRoute
  '/apps/$companyId/drivers/': typeof AppsCompanyIdDriversIndexRoute
  '/apps/$companyId/fleets/': typeof AppsCompanyIdFleetsIndexRoute
  '/apps/$companyId/members/': typeof AppsCompanyIdMembersIndexRoute
  '/apps/$companyId/orders/': typeof AppsCompanyIdOrdersIndexRoute
  '/apps/$companyId/tracking/': typeof AppsCompanyIdTrackingIndexRoute
  '/apps/$companyId/orders/$orderRef/edit': typeof AppsCompanyIdOrdersOrderRefEditRoute
  '/apps/$companyId/billing/history/': typeof AppsCompanyIdBillingHistoryIndexRoute
  '/apps/$companyId/drivers/$driverId/': typeof AppsCompanyIdDriversDriverIdIndexRoute
  '/apps/$companyId/fleets/$vehicleId/': typeof AppsCompanyIdFleetsVehicleIdIndexRoute
  '/apps/$companyId/orders/$orderRef/': typeof AppsCompanyIdOrdersOrderRefIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps/$companyId'
    | '/auth/sign-in'
    | '/register/'
    | '/auth/sign-up/$'
    | '/apps/$companyId/'
    | '/apps/$companyId/orders/create'
    | '/apps/$companyId/billing/'
    | '/apps/$companyId/dashboard/'
    | '/apps/$companyId/dispatch/'
    | '/apps/$companyId/drivers/'
    | '/apps/$companyId/fleets/'
    | '/apps/$companyId/members/'
    | '/apps/$companyId/orders/'
    | '/apps/$companyId/tracking/'
    | '/apps/$companyId/orders/$orderRef/edit'
    | '/apps/$companyId/billing/history/'
    | '/apps/$companyId/drivers/$driverId/'
    | '/apps/$companyId/fleets/$vehicleId/'
    | '/apps/$companyId/orders/$orderRef/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/register'
    | '/auth/sign-up/$'
    | '/apps/$companyId'
    | '/apps/$companyId/orders/create'
    | '/apps/$companyId/billing'
    | '/apps/$companyId/dashboard'
    | '/apps/$companyId/dispatch'
    | '/apps/$companyId/drivers'
    | '/apps/$companyId/fleets'
    | '/apps/$companyId/members'
    | '/apps/$companyId/orders'
    | '/apps/$companyId/tracking'
    | '/apps/$companyId/orders/$orderRef/edit'
    | '/apps/$companyId/billing/history'
    | '/apps/$companyId/drivers/$driverId'
    | '/apps/$companyId/fleets/$vehicleId'
    | '/apps/$companyId/orders/$orderRef'
  id:
    | '__root__'
    | '/'
    | '/apps/$companyId'
    | '/auth/sign-in'
    | '/register/'
    | '/auth/sign-up/$'
    | '/apps/$companyId/'
    | '/apps/$companyId/orders/create'
    | '/apps/$companyId/billing/'
    | '/apps/$companyId/dashboard/'
    | '/apps/$companyId/dispatch/'
    | '/apps/$companyId/drivers/'
    | '/apps/$companyId/fleets/'
    | '/apps/$companyId/members/'
    | '/apps/$companyId/orders/'
    | '/apps/$companyId/tracking/'
    | '/apps/$companyId/orders/$orderRef/edit'
    | '/apps/$companyId/billing/history/'
    | '/apps/$companyId/drivers/$driverId/'
    | '/apps/$companyId/fleets/$vehicleId/'
    | '/apps/$companyId/orders/$orderRef/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsCompanyIdRouteRoute: typeof AppsCompanyIdRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$companyId': {
      id: '/apps/$companyId'
      path: '/apps/$companyId'
      fullPath: '/apps/$companyId'
      preLoaderRoute: typeof AppsCompanyIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$companyId/': {
      id: '/apps/$companyId/'
      path: '/'
      fullPath: '/apps/$companyId/'
      preLoaderRoute: typeof AppsCompanyIdIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/auth/sign-up/$': {
      id: '/auth/sign-up/$'
      path: '/auth/sign-up/$'
      fullPath: '/auth/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$companyId/tracking/': {
      id: '/apps/$companyId/tracking/'
      path: '/tracking'
      fullPath: '/apps/$companyId/tracking/'
      preLoaderRoute: typeof AppsCompanyIdTrackingIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/orders/': {
      id: '/apps/$companyId/orders/'
      path: '/orders'
      fullPath: '/apps/$companyId/orders/'
      preLoaderRoute: typeof AppsCompanyIdOrdersIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/members/': {
      id: '/apps/$companyId/members/'
      path: '/members'
      fullPath: '/apps/$companyId/members/'
      preLoaderRoute: typeof AppsCompanyIdMembersIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/fleets/': {
      id: '/apps/$companyId/fleets/'
      path: '/fleets'
      fullPath: '/apps/$companyId/fleets/'
      preLoaderRoute: typeof AppsCompanyIdFleetsIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/drivers/': {
      id: '/apps/$companyId/drivers/'
      path: '/drivers'
      fullPath: '/apps/$companyId/drivers/'
      preLoaderRoute: typeof AppsCompanyIdDriversIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/dispatch/': {
      id: '/apps/$companyId/dispatch/'
      path: '/dispatch'
      fullPath: '/apps/$companyId/dispatch/'
      preLoaderRoute: typeof AppsCompanyIdDispatchIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/dashboard/': {
      id: '/apps/$companyId/dashboard/'
      path: '/dashboard'
      fullPath: '/apps/$companyId/dashboard/'
      preLoaderRoute: typeof AppsCompanyIdDashboardIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/billing/': {
      id: '/apps/$companyId/billing/'
      path: '/billing'
      fullPath: '/apps/$companyId/billing/'
      preLoaderRoute: typeof AppsCompanyIdBillingIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/orders/create': {
      id: '/apps/$companyId/orders/create'
      path: '/orders/create'
      fullPath: '/apps/$companyId/orders/create'
      preLoaderRoute: typeof AppsCompanyIdOrdersCreateRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/orders/$orderRef/': {
      id: '/apps/$companyId/orders/$orderRef/'
      path: '/orders/$orderRef'
      fullPath: '/apps/$companyId/orders/$orderRef/'
      preLoaderRoute: typeof AppsCompanyIdOrdersOrderRefIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/fleets/$vehicleId/': {
      id: '/apps/$companyId/fleets/$vehicleId/'
      path: '/fleets/$vehicleId'
      fullPath: '/apps/$companyId/fleets/$vehicleId/'
      preLoaderRoute: typeof AppsCompanyIdFleetsVehicleIdIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/drivers/$driverId/': {
      id: '/apps/$companyId/drivers/$driverId/'
      path: '/drivers/$driverId'
      fullPath: '/apps/$companyId/drivers/$driverId/'
      preLoaderRoute: typeof AppsCompanyIdDriversDriverIdIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/billing/history/': {
      id: '/apps/$companyId/billing/history/'
      path: '/billing/history'
      fullPath: '/apps/$companyId/billing/history/'
      preLoaderRoute: typeof AppsCompanyIdBillingHistoryIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/orders/$orderRef/edit': {
      id: '/apps/$companyId/orders/$orderRef/edit'
      path: '/orders/$orderRef/edit'
      fullPath: '/apps/$companyId/orders/$orderRef/edit'
      preLoaderRoute: typeof AppsCompanyIdOrdersOrderRefEditRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
  }
}

interface AppsCompanyIdRouteRouteChildren {
  AppsCompanyIdIndexRoute: typeof AppsCompanyIdIndexRoute
  AppsCompanyIdOrdersCreateRoute: typeof AppsCompanyIdOrdersCreateRoute
  AppsCompanyIdBillingIndexRoute: typeof AppsCompanyIdBillingIndexRoute
  AppsCompanyIdDashboardIndexRoute: typeof AppsCompanyIdDashboardIndexRoute
  AppsCompanyIdDispatchIndexRoute: typeof AppsCompanyIdDispatchIndexRoute
  AppsCompanyIdDriversIndexRoute: typeof AppsCompanyIdDriversIndexRoute
  AppsCompanyIdFleetsIndexRoute: typeof AppsCompanyIdFleetsIndexRoute
  AppsCompanyIdMembersIndexRoute: typeof AppsCompanyIdMembersIndexRoute
  AppsCompanyIdOrdersIndexRoute: typeof AppsCompanyIdOrdersIndexRoute
  AppsCompanyIdTrackingIndexRoute: typeof AppsCompanyIdTrackingIndexRoute
  AppsCompanyIdOrdersOrderRefEditRoute: typeof AppsCompanyIdOrdersOrderRefEditRoute
  AppsCompanyIdBillingHistoryIndexRoute: typeof AppsCompanyIdBillingHistoryIndexRoute
  AppsCompanyIdDriversDriverIdIndexRoute: typeof AppsCompanyIdDriversDriverIdIndexRoute
  AppsCompanyIdFleetsVehicleIdIndexRoute: typeof AppsCompanyIdFleetsVehicleIdIndexRoute
  AppsCompanyIdOrdersOrderRefIndexRoute: typeof AppsCompanyIdOrdersOrderRefIndexRoute
}

const AppsCompanyIdRouteRouteChildren: AppsCompanyIdRouteRouteChildren = {
  AppsCompanyIdIndexRoute: AppsCompanyIdIndexRoute,
  AppsCompanyIdOrdersCreateRoute: AppsCompanyIdOrdersCreateRoute,
  AppsCompanyIdBillingIndexRoute: AppsCompanyIdBillingIndexRoute,
  AppsCompanyIdDashboardIndexRoute: AppsCompanyIdDashboardIndexRoute,
  AppsCompanyIdDispatchIndexRoute: AppsCompanyIdDispatchIndexRoute,
  AppsCompanyIdDriversIndexRoute: AppsCompanyIdDriversIndexRoute,
  AppsCompanyIdFleetsIndexRoute: AppsCompanyIdFleetsIndexRoute,
  AppsCompanyIdMembersIndexRoute: AppsCompanyIdMembersIndexRoute,
  AppsCompanyIdOrdersIndexRoute: AppsCompanyIdOrdersIndexRoute,
  AppsCompanyIdTrackingIndexRoute: AppsCompanyIdTrackingIndexRoute,
  AppsCompanyIdOrdersOrderRefEditRoute: AppsCompanyIdOrdersOrderRefEditRoute,
  AppsCompanyIdBillingHistoryIndexRoute: AppsCompanyIdBillingHistoryIndexRoute,
  AppsCompanyIdDriversDriverIdIndexRoute:
    AppsCompanyIdDriversDriverIdIndexRoute,
  AppsCompanyIdFleetsVehicleIdIndexRoute:
    AppsCompanyIdFleetsVehicleIdIndexRoute,
  AppsCompanyIdOrdersOrderRefIndexRoute: AppsCompanyIdOrdersOrderRefIndexRoute,
}

const AppsCompanyIdRouteRouteWithChildren =
  AppsCompanyIdRouteRoute._addFileChildren(AppsCompanyIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsCompanyIdRouteRoute: AppsCompanyIdRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
