/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppsCompanyIdRouteRouteImport } from './routes/apps/$companyId/route'
import { Route as AppsCompanyIdIndexRouteImport } from './routes/apps/$companyId/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AuthSignUpSplatRouteImport } from './routes/auth/sign-up.$'
import { Route as AppsCompanyIdDashboardRouteImport } from './routes/apps/$companyId/dashboard'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as AppsCompanyIdOrdersIndexRouteImport } from './routes/apps/$companyId/orders/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AppsCompanyIdOrdersCreateRouteImport } from './routes/apps/$companyId/orders/create'
import { Route as AppsCompanyIdOrdersOrderRefIndexRouteImport } from './routes/apps/$companyId/orders/$orderRef/index'
import { Route as AppsCompanyIdOrdersOrderRefEditRouteImport } from './routes/apps/$companyId/orders/$orderRef/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsCompanyIdRouteRoute = AppsCompanyIdRouteRouteImport.update({
  id: '/apps/$companyId',
  path: '/apps/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsCompanyIdIndexRoute = AppsCompanyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsCompanyIdRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/auth/sign-up/$',
  path: '/auth/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsCompanyIdDashboardRoute = AppsCompanyIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppsCompanyIdRouteRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsCompanyIdOrdersIndexRoute =
  AppsCompanyIdOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsCompanyIdOrdersCreateRoute =
  AppsCompanyIdOrdersCreateRouteImport.update({
    id: '/orders/create',
    path: '/orders/create',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdOrdersOrderRefIndexRoute =
  AppsCompanyIdOrdersOrderRefIndexRouteImport.update({
    id: '/orders/$orderRef/',
    path: '/orders/$orderRef/',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)
const AppsCompanyIdOrdersOrderRefEditRoute =
  AppsCompanyIdOrdersOrderRefEditRouteImport.update({
    id: '/orders/$orderRef/edit',
    path: '/orders/$orderRef/edit',
    getParentRoute: () => AppsCompanyIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/$companyId': typeof AppsCompanyIdRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/apps/$companyId/dashboard': typeof AppsCompanyIdDashboardRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/apps/$companyId/': typeof AppsCompanyIdIndexRoute
  '/apps/$companyId/orders/create': typeof AppsCompanyIdOrdersCreateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/apps/$companyId/orders/': typeof AppsCompanyIdOrdersIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/apps/$companyId/orders/$orderRef/edit': typeof AppsCompanyIdOrdersOrderRefEditRoute
  '/apps/$companyId/orders/$orderRef/': typeof AppsCompanyIdOrdersOrderRefIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/apps/$companyId/dashboard': typeof AppsCompanyIdDashboardRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/apps/$companyId': typeof AppsCompanyIdIndexRoute
  '/apps/$companyId/orders/create': typeof AppsCompanyIdOrdersCreateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/apps/$companyId/orders': typeof AppsCompanyIdOrdersIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/apps/$companyId/orders/$orderRef/edit': typeof AppsCompanyIdOrdersOrderRefEditRoute
  '/apps/$companyId/orders/$orderRef': typeof AppsCompanyIdOrdersOrderRefIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/$companyId': typeof AppsCompanyIdRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/apps/$companyId/dashboard': typeof AppsCompanyIdDashboardRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/apps/$companyId/': typeof AppsCompanyIdIndexRoute
  '/apps/$companyId/orders/create': typeof AppsCompanyIdOrdersCreateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/apps/$companyId/orders/': typeof AppsCompanyIdOrdersIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/apps/$companyId/orders/$orderRef/edit': typeof AppsCompanyIdOrdersOrderRefEditRoute
  '/apps/$companyId/orders/$orderRef/': typeof AppsCompanyIdOrdersOrderRefIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps/$companyId'
    | '/auth/sign-in'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/onboarding/'
    | '/apps/$companyId/dashboard'
    | '/auth/sign-up/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/apps/$companyId/'
    | '/apps/$companyId/orders/create'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/apps/$companyId/orders/'
    | '/demo/start/ssr/'
    | '/apps/$companyId/orders/$orderRef/edit'
    | '/apps/$companyId/orders/$orderRef/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/onboarding'
    | '/apps/$companyId/dashboard'
    | '/auth/sign-up/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/apps/$companyId'
    | '/apps/$companyId/orders/create'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/apps/$companyId/orders'
    | '/demo/start/ssr'
    | '/apps/$companyId/orders/$orderRef/edit'
    | '/apps/$companyId/orders/$orderRef'
  id:
    | '__root__'
    | '/'
    | '/apps/$companyId'
    | '/auth/sign-in'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/onboarding/'
    | '/apps/$companyId/dashboard'
    | '/auth/sign-up/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/apps/$companyId/'
    | '/apps/$companyId/orders/create'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/apps/$companyId/orders/'
    | '/demo/start/ssr/'
    | '/apps/$companyId/orders/$orderRef/edit'
    | '/apps/$companyId/orders/$orderRef/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsCompanyIdRouteRoute: typeof AppsCompanyIdRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$companyId': {
      id: '/apps/$companyId'
      path: '/apps/$companyId'
      fullPath: '/apps/$companyId'
      preLoaderRoute: typeof AppsCompanyIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$companyId/': {
      id: '/apps/$companyId/'
      path: '/'
      fullPath: '/apps/$companyId/'
      preLoaderRoute: typeof AppsCompanyIdIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up/$': {
      id: '/auth/sign-up/$'
      path: '/auth/sign-up/$'
      fullPath: '/auth/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$companyId/dashboard': {
      id: '/apps/$companyId/dashboard'
      path: '/dashboard'
      fullPath: '/apps/$companyId/dashboard'
      preLoaderRoute: typeof AppsCompanyIdDashboardRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$companyId/orders/': {
      id: '/apps/$companyId/orders/'
      path: '/orders'
      fullPath: '/apps/$companyId/orders/'
      preLoaderRoute: typeof AppsCompanyIdOrdersIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$companyId/orders/create': {
      id: '/apps/$companyId/orders/create'
      path: '/orders/create'
      fullPath: '/apps/$companyId/orders/create'
      preLoaderRoute: typeof AppsCompanyIdOrdersCreateRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/orders/$orderRef/': {
      id: '/apps/$companyId/orders/$orderRef/'
      path: '/orders/$orderRef'
      fullPath: '/apps/$companyId/orders/$orderRef/'
      preLoaderRoute: typeof AppsCompanyIdOrdersOrderRefIndexRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
    '/apps/$companyId/orders/$orderRef/edit': {
      id: '/apps/$companyId/orders/$orderRef/edit'
      path: '/orders/$orderRef/edit'
      fullPath: '/apps/$companyId/orders/$orderRef/edit'
      preLoaderRoute: typeof AppsCompanyIdOrdersOrderRefEditRouteImport
      parentRoute: typeof AppsCompanyIdRouteRoute
    }
  }
}

interface AppsCompanyIdRouteRouteChildren {
  AppsCompanyIdDashboardRoute: typeof AppsCompanyIdDashboardRoute
  AppsCompanyIdIndexRoute: typeof AppsCompanyIdIndexRoute
  AppsCompanyIdOrdersCreateRoute: typeof AppsCompanyIdOrdersCreateRoute
  AppsCompanyIdOrdersIndexRoute: typeof AppsCompanyIdOrdersIndexRoute
  AppsCompanyIdOrdersOrderRefEditRoute: typeof AppsCompanyIdOrdersOrderRefEditRoute
  AppsCompanyIdOrdersOrderRefIndexRoute: typeof AppsCompanyIdOrdersOrderRefIndexRoute
}

const AppsCompanyIdRouteRouteChildren: AppsCompanyIdRouteRouteChildren = {
  AppsCompanyIdDashboardRoute: AppsCompanyIdDashboardRoute,
  AppsCompanyIdIndexRoute: AppsCompanyIdIndexRoute,
  AppsCompanyIdOrdersCreateRoute: AppsCompanyIdOrdersCreateRoute,
  AppsCompanyIdOrdersIndexRoute: AppsCompanyIdOrdersIndexRoute,
  AppsCompanyIdOrdersOrderRefEditRoute: AppsCompanyIdOrdersOrderRefEditRoute,
  AppsCompanyIdOrdersOrderRefIndexRoute: AppsCompanyIdOrdersOrderRefIndexRoute,
}

const AppsCompanyIdRouteRouteWithChildren =
  AppsCompanyIdRouteRoute._addFileChildren(AppsCompanyIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsCompanyIdRouteRoute: AppsCompanyIdRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
